#==========================================================================
#
#	XPL makefile for 16-bit DOS using DJGPP
#	This makefile is for GNU make
#	DJGPP gcc version 4.7.1 (generates 32-bit code)
#
#==========================================================================
# To run under FreeDOS 1.2
#	set PATH=C:\DEVEL\DJGPP\BIN;%path%
#	set DJGPP=C:\DEVEL\DJGPP\DJGPP.ENV
#	make -f makefile.dj
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Path variables and compiler options
#------------------------------------------------------------------------------

XPLDIR = ..
XPL = $(XPLDIR)\xpl
TARGETS = xformat.exe xxref.exe
LIBXPL = $(XPLDIR)\libxpl.a

CFLAGS  = -I. -I$(XPLDIR)
LDLIBS	= $(LIBXPL)

#------------------------------------------------------------------------------
# Rules
#------------------------------------------------------------------------------

%.exe:	%.o
	$(LINK.o) $^ $(LOADLIBES) $(LDLIBS) -o $@

%.c:	%.xpl
	$(XPL) $< -o $@

#------------------------------------------------------------------------------
# Default target
#------------------------------------------------------------------------------

all:	$(TARGETS)
	copy xformat.exe $(XPLDIR)
	copy xxref.exe $(XPLDIR)

#------------------------------------------------------------------------------
# Dependancies
#------------------------------------------------------------------------------

xformat.c:	xformat.xpl
xformat.o:	xformat.c
xformat.exe:	xformat.o

xxref.c:	xxref.xpl
xxref.o:	xxref.c
xxref.exe:	xxref.o

#------------------------------------------------------------------------------
# cleanup
#------------------------------------------------------------------------------

clean:
	@del *.o
	@del *.c
	@del *.xh
	@del xxref.exe
	@del xformat.exe

#------------------------------------------------------------------------------
# misc stuff
#------------------------------------------------------------------------------

info:
	@echo CC=$(COMPILE.c)
	@echo LD=$(LINK.o)
	@echo LDLIBS=$(LDLIBS)

